name: payu_api
description: Flutter package with Payu networking mechanism.
version: 1.0.6
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.3 <4.10.0'
  flutter: ">=3.22.2"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  payu_core:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_core
dev_dependencies:
  build_runner: ^2.4.11
  dependency_validator: ^4.1.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - ssl/entrust.pem
    - ssl/sectigoR46.pem
